spring:
  application:
    name: algoqueue
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_SCHEME}?serverTimezone=${MYSQL_TIMEZONE}
    hikari:
      maximum-pool-size: 5
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_CODE}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    session:
      timeout: 30m

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace